name: markdown_web
author: suinua
description: convert md files to html
branding:
  icon: plus
  color: green
inputs:
  articles_directory_path:
    description: 'articles directory path'
    required: true
  github_token:
    description: ''
    required: true
runs:
  using: docker
  image: Dockerfile
