name: markdown_web
author: suinua
description: convert md files to html
branding:
  icon: plus
  color: green
inputs:
  articlesDirectoryPath:
    description: 'path to articles directory'
    required: true
runs:
  using: docker
  image: Dockerfile
