name: markdown_web

description: convert md files to html
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  markdown: ^4.0.1
  path: ^1.8.0
  uuid: ^3.0.6
  http: ^0.13.4
  universal_html: ^2.0.8

dev_dependencies:
  pedantic: ^1.10.0
