name: markdown_web

description: convert md files to html
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  github: ^9.0.0
  markdown: ^4.0.1
  path: ^1.8.0
  uuid: ^3.0.6

dev_dependencies:
  pedantic: ^1.10.0
