name: execute_itself

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: suinua/markdown_web@master
        with:
          articles_directory_path: 'articles'
          index_file_path: 'articles/index.md'
          github_token: ${{ secrets.GITHUB_TOKEN }}